import { GetServerSideProps } from "next";
import Head from "next/head";
import React from "react";
import Header from "../../components/Header";
import { getCountry } from "../../utils/apis/CountryApi";
import { toCountry } from "../../utils/helpers/Casters";

interface CountryDetailsProps {
  countryStr: string;
}

export const getServerSideProps: GetServerSideProps<
  CountryDetailsProps
> = async (context) => {
  // const json = "../../public/CountryProfileList.json";
  // console.log(context);
  // const countryListRaw: any[] = Array.from(
  //   await import("../../public/CountryProfileList.json"),
  // );
  // console.log(await countryListRaw());

  const target = JSON.stringify(
    await getCountry((context.query.details + "").toLowerCase()),
  );
  // const countryTarget: Country = toCountry(target);
  // console.log(countryTarget);

  return {
    props: { countryStr: target },
    notFound: !target,
  };
};

function Details({ countryStr }: CountryDetailsProps) {
  //   const router = useRouter();
  //   const { country } = router.query;
  // console.log(country.name.nativeName);
  // console.log(country.languages);
  // getting name list
  const country = toCountry(JSON.parse(countryStr)[0]);
  const countryName = country.name;
  const nameList = countryName.nativeName.filter(
    (nameItem) => nameItem.official !== countryName.official,
  );

  // render parts
  const RENDER_FLAG = () => (
    <div className="self-center sm:self-start">
      <img
        className="rounded-lg shadow-lg ring-4 ring-slate-600/30"
        src={country.flags.png}
      />
    </div>
  );

  const RENDER_NAME = () => (
    <h1 className="text-5xl font-black">
      {countryName.common} {country.flag}
    </h1>
  );
  const RENDER_OTHER_NAMES = () => (
    <div className="flex flex-wrap gap-2">
      <span className="font-bold">Also known as :</span>
      <div className="flex flex-wrap gap-x-1">
        <h2 className="">{countryName.official}</h2>
        {nameList.map((nameItem) => (
          <>
            &mdash;
            <h2 key={nameItem.code} className="">
              {nameItem.official}
            </h2>
          </>
        ))}
      </div>
    </div>
  );

  const RENDER_CAPITALS = () =>
    country.capital && (
      <div className="flex flex-wrap gap-2">
        <span className="font-bold">
          Capital{country.capital.length > 1 ? "s" : ""} :
        </span>
        {country.capital.map((capital) => (
          <>
            <span key={capital}>{capital}</span>
            <span className="last:hidden">&mdash;</span>
          </>
        ))}
      </div>
    );

  const RENDER_LANGUAGES = () => (
    <div className="flex flex-wrap">
      <span className="mr-2 font-bold">
        Language{country.languages.length > 1 ? "s" : ""} spoken :
      </span>
      <span className="">
        {country.languages.map((langItem) => langItem.name).join(" — ")}
      </span>
    </div>
  );

  const RENDER_REGIONS = () => (
    <>
      <div>
        <span className="font-bold">Continent :</span>{" "}
        {country.continents.join(", ")}
      </div>
      <div>
        <span className="font-bold">Region :</span> {country.region}
      </div>
      {country.subregion && (
        <div>
          <span className="font-bold">Subregion :</span> {country.subregion}
        </div>
      )}
    </>
  );

  const RENDER_AREA = () => (
    <div>
      <span className="font-bold">Area size :</span>{" "}
      {country.area.toLocaleString() + " km^2"}
    </div>
  );

  const RENDER_CURRENCIES = () =>
    country.currencies[0] && (
      <div className="flex flex-wrap">
        <span className="mr-2 font-bold">
          Currenc{country.currencies.length > 1 ? "ies" : "y"} :
        </span>
        <span className="">
          {country.currencies.map(
            (currItem) =>
              `${currItem.name} (${currItem.code} / ${currItem.symbol})`,
          )}
        </span>
      </div>
    );

  return (
    <>
      <Head>
        <title>{countryName.common}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="pt-16">
        <div className="flex flex-col gap-8 p-8 sm:flex-row">
          {RENDER_FLAG()}
          <div className="flex-1">
            <div className="grid gap-4">
              {RENDER_NAME()}
              {/* <h2 className="text-3xl font-bold">{cName.official}</h2> */}
              {RENDER_OTHER_NAMES()}
              {RENDER_CAPITALS()}
              {RENDER_LANGUAGES()}
              {RENDER_REGIONS()}
              {RENDER_AREA()}
              {RENDER_CURRENCIES()}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default Details;
